<!-- CREAR UNA COPIA DE IRPF.PHP CON GET EN VEZ DE POST
  Y CONTROLAR LOS ERRORES DE ENVIAR EL FORMULARIO VACIO -->

  <!-- CONTROLAR EN TODOS LOS DEMAS FORMULARIOS HECHOS CON 
   POST QUE SI SE MANDAN LOS CAMPOS VACIOS, SE MUESTRE UN MENSAJE. -->